- CHANGELOG.md
- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
Relates to https://ticket.vshn.net/browse/APPU-2749
> Initial implementation

- .sync.yml
> Add config for modulesync

- component/main.jsonnet
- docs/modules/ROOT/pages/index.adoc
Make use of component openshift4-operators to create subscriptions and operatorgroup.
Depends on https://github.com/appuio/component-openshift4-operators/pull/1
Fixes #7
> Deploy elasticsearch-operator cluster-scoped

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Add clusterLogForwarding

- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Support enabling json parsing for namespace groups.

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Allow infrastructure and audit log cutomization.

- class/openshift4-logging.yml
- component/alertrules.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
See https://github.com/appuio/component-openshift4-monitoring/pull/135 for the corresponding openshift4-monitoring PR.
Fixes #64 
> Fetch and render elasticsearch-operator alert rules

- class/defaults.yml
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
> Remove curator config, as it was removed

- alerts.txt
- class/defaults.yml
- component/extracted_alerts/release-5.6/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.6/fluentd_prometheus_alerts.yaml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/40_es_alertrules.yaml
> Bump default logging stack version to 5.6

- docs/modules/ROOT/pages/how-tos/upgrade-v1.x-v2.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add how-to migrate to v2.x

- component/app.jsonnet
> Enable Vault secret support in ArgoCD app

- class/defaults.yml
- component/app.jsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
> Fix missing pruneNamespacesInterval when using Lokistack

- component/alertrules.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
> Fix runbook_url not rendered correctly

- component/alertrules.libsonnet
- tests/golden/lokistack/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
> Fix prometheus rules naming

- .cruft.json
- Makefile.vars.mk
- docs/modules/ROOT/pages/how-tos/migrate-to-lokistack.adoc
- docs/modules/ROOT/pages/how-tos/switch-to-lokistack.adoc
- docs/modules/ROOT/partials/nav.adoc
> Document Switch from Elasticsearch to Lokistack

- CODEOWNERS
changelog.
- [-] Update the documentation.
- [-] Link this PR to related issues or PRs.
> Add Aldebaran Tech as CodeOwner

- alerts.txt
- class/defaults.yml
- component/extracted_alerts/release-5.7/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.7/fluentd_prometheus_alerts.yaml
- component/extracted_alerts/release-5.7/lokistack_prometheus_alerts.yaml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/20_subscriptions.yaml
> Bump default logging stack version to 5.7

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/00_namespace.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_es_machineconfig.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_es_netpol.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/multilineerr.yml
> Support detecting multiline errors

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/how-tos/upgrade-v2.x-v3.x.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
> Move deprecated collector config

- class/defaults.yml
- docs/modules/ROOT/pages/how-tos/upgrade-v2.x-v3.x.adoc
- tests/elasticsearch.yml
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/elasticsearch/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
> Vector is now the default logging collector

- component/elasticsearch.libsonnet
- component/es_workaround.libsonnet
- tests/golden/elasticsearch/openshift4-logging/openshift4-logging/40_es_operator_metrics_token.yaml
> Manually generate missing Elasticsearch Operator metrics token

- component/main.jsonnet
> Refactor OperatorGroup and Subscription generation code

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/50_loki_stack.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/50_loki_stack.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_loki_stack.yaml
With Logging 5.9 Lokistack uses a new storage schema. The new schema is valid from 2024-09-01.
changelog.
> Update Lokistack storage scheme to v13

- class/defaults.yml
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/20_subscriptions.yaml
> Fix Cluster Logging Operator resource requests/limits

- component/log_forwarder.libsonnet
- tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
> Fix filters not applied to LogForwarder

- .cruft.json
- class/defaults.yml
- class/openshift4-logging.yml
- component/app.jsonnet
Template version: main (`f12cbb4`)
changelog.
> Update from template

- component/log_forwarder.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
Remove referencing defaults in pipelines.
changelog.
> Fix ClusterLogForwarder default pipelines

- docs/modules/ROOT/pages/how-tos/enable-log-retention.adoc
- docs/modules/ROOT/partials/nav.adoc
> Document how to set log retention

- component/log_lokistack.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_loki_plugin.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_loki_plugin.yaml
> Fix initial sync by skipping dry-run for `UIPlugin`

- class/defaults.yml
- component/log_forwarder.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/master.yml
> Allow disable sending application logs to internal Loki Stack

- class/defaults.yml
- component/main.jsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
Make the observability operators resources configurable.
changelog.
> Fix observability operator memory limits

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/master/openshift4-logging/openshift4-logging/99_configmaps.yaml
- tests/master.yml
> Support creating configmaps in component

- component/log_lokistack.libsonnet
> Remove unused patch-operator import

- component/log_lokistack.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_loki_rbac.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_loki_rbac.yaml
Default  ClusterRoles admin, edit and view can access live logs but not aggregated logs.
changelog.
> Aggregate application log permissions to admin, edit, view
