appuio/component-openshift4-logging

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
In OpenShift 4.7 Red Hat introduced an OpenShift version independent
logging stack starting with the version 5.0. Since version 5.1 there
are two channels stable and stable-5.1. Choosing the stable channel
allows never have to care about the interoperability as the specific
OpenShift version delivers the right version via the operator
marketplace.
> Change the logging channel to stable

- docs/modules/ROOT/pages/how-tos/upgrade-v0.1-v1.x.adoc
> Add migration guide from v0.1 to v1.x

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Add JSON log parsing

- component/main.jsonnet
If cluster log forwarding is enabled with the audit-logs pipeline the log storage quickly fills up with audit logs.
Removing the pipeline as audit-logs are not enabled in the default config either.
> Remove audit-logs pipeline from log forwarding

- class/defaults.yml
- class/openshift4-logging.yml
- component/alertrules.libsonnet
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
Move prometheus rules from openshift4-monitoring component to logging component.
> Add prometheus rules

- class/defaults.yml
- component/alertrules.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/pages/runbooks/SYN_ElasticsearchExpectNodeToReachDiskWatermark.adoc
- docs/modules/ROOT/pages/runbooks/_RuleTemplate.adoc
- docs/modules/ROOT/partials/nav.adoc
- docs/modules/ROOT/partials/runbooks/contribution_note.adoc
Fire alert `SYN_ElasticsearchExpectNodeToReachDiskWatermark` if the disk storage on a node is predicted to run out.
Includes runbook.
> Alerting: Predict Elasticsearch storage watermark reached

- class/defaults.yml
- component/kibana-host.libsonnet
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
Allows setting a custom host for Kibana. Updating the URLs in the console is correctly handled by the operator.
> Allow setting custom kibana host

- class/defaults.yml
- component/alertrules.libsonnet
- component/main.jsonnet
- component/metrics.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/70_monitoring_namespace.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/70_monitoring_networkpolicy.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/70_monitoring_servicemonitors.yaml
- tests/syn-monitoring.yml
Configure ServiceMonitors to scrape Elasticsearch, fluentd and logging-operator metrics in the vendor-independent monitoring stack.
> Add logic to configure ServiceMonitors

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- renovate.json
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/syn-monitoring/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
We introduce a new parameter `version` which is used to define default values for parameters `channel` and `alerts`. This change is backwards-compatible, as users can still override parameters `channel` and `alerts`.
> Expose cluster-logging version in parameter `version`

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- class/openshift4-logging.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/00_namespace.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/40_journald_configs.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/50_networkpolicy.yaml
- tests/golden/release-5.5/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
- tests/release-5.5.yml
We need to specify different locations of the fluentd alerts YAML file in the upstream repository based on the logging stack release, as the file got moved to `files/collector/fluentd_prometheus_alerts.yaml` for release 5.5.
We implement this as a lookup map in the component class. Because we don't have a way to implement a fallback value for keys which aren't present in the lookup map, this change removes out-of-the-box support for future logging stack versions.
Fixes #69
> Switch fetching of fluentd alert YAML file to lookup map 

- component/alertrules.libsonnet
- tests/defaults.yml
- tests/release-5.4.yml
- tests/syn-monitoring.yml
We've added a component library for patching and filtering alerts in https://github.com/appuio/component-openshift4-monitoring/pull/136 which is released in component opneshift4-monitoring v2.9.0.
This PR uses the library to replace the copy-pasted logic to patch alerts managed by this component.
> Use `alert-patching.libsonnet` to render our alerts

- .cruft.json
- .editorconfig
- .github/workflows/download-alerts.yaml
- .github/workflows/test.yaml
- .yamllint.yml
- Makefile
- Makefile.vars.mk
- alerts.txt
- class/openshift4-logging.yml
- component/alertrules.libsonnet
- component/extracted_alerts/master/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/master/fluentd_prometheus_alerts.yaml
- component/extracted_alerts/release-5.2/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.2/fluentd_prometheus_alerts.yaml
- component/extracted_alerts/release-5.3/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.3/fluentd_prometheus_alerts.yaml
- component/extracted_alerts/release-5.4/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.4/fluentd_prometheus_alerts.yaml
- component/extracted_alerts/release-5.5/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.5/fluentd_prometheus_alerts.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/00_namespace.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/40_journald_configs.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/50_networkpolicy.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_prometheus_rules.yaml
- tests/master.yml
- tools/download-upstream-alerts.sh
This PR adds a make target and script to download upstream alerts from either yaml or Go top level constants/variables.
The workflow runs once a day during the week and creates or updates the existing [PR](https://github.com/appuio/component-openshift4-logging/pull/79/commits/01bfaf1645e65a511ea962d25df1155fab823097). 
Fixes #47 and #74.
Uses (the very experimental) https://github.com/bastjan/declextract to extract declarations.
The PR is quite big but the important parts are:
- [download-alerts.yaml](https://github.com/appuio/component-openshift4-logging/blob/bd906f9a2b3356cc837892c8359e97d28713a62c/.github/workflows/download-alerts.yaml)
- [download-upstream-alerts.sh](https://github.com/appuio/component-openshift4-logging/blob/bd906f9a2b3356cc837892c8359e97d28713a62c/tools/download-upst …
> Extract upstream alerts from Go files

- component/loki.libsonnet
- tests/golden/lokistack/openshift4-logging/openshift4-logging/50_loki_console_patch.yaml
- tests/lokistack.yml
Enables the logging view plugin in the OpenShift console by patching the cluster-scoped console object.
changelog.
> Enable logging view plugin in console

- Makefile.vars.mk
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
The latest Commodore version (which will become v1.15.0) updates Kapitan to 0.31.0 and uses Kapitan's new "literal" multi-line YAML string formatting feature.
Since the alert rules contain long YAML strings and YAML strings which contain literal newlines, they get formatted differently due to this change.
Follow-up to #98 
changelog.
> Update golden test outputs for latest Commodore

- class/defaults.yml
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
Previously, the component set parameter `openshift4_console` to `null` (an empty YAML value is treated as null) when the EFK stack is being deployed, this breaks catalog compilation for existing setups because it wipes the openshift4-console component defaults, if this component's defaults are included after the console defaults.
This commit fixes the bug by setting `openshift4_console: {}` if the EFK stack is being deployed.
Fixes #97 
changelog.
> Fix openshift-console config when deploying EFK stack

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/lokistack/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/20_subscriptions.yaml
The requests and limits are derived from metrics of existing deployments. Resource usage on all operators looks very stable.
changelog.
> Add resource requests and limits to operator subscriptions

- class/defaults.yml
- component/alertrules.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
- tests/golden/release-5.4/openshift4-logging/openshift4-logging/60_elasticsearch_alerts.yaml
Disable all `severity=info` alerts, and add a few low-value alerts to the ignore list in `class/defaults.yml`
changelog.
> Disable low-value alerts by default

- .github/workflows/test.yaml
- component/loki.libsonnet
- tests/golden/lokistack/openshift4-logging/openshift4-logging/50_loki_stack.yaml
This allows ArgoCD to continue with syncing the component on first install.
changelog.
> Skip missing `LokiStack` CRD in ArgoCD dry-run

- class/defaults.yml
- component/loki.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/lokistack/openshift4-logging/openshift4-logging/50_loki_rbac.yaml
> Add support for configuring log access in LokiStack for `cluster-reader`

- component/loki.libsonnet
- tests/golden/lokistack/openshift4-logging/openshift4-logging/50_loki_stack.yaml
Cluster-logging 5.8 introduces PDBs for the Loki stack. Unfortunately the PDBs are created unconditionally, and block node drains when deploying LokiStack with `1x.demo`.
We adjust the replica count for the LokiStack read path (gateway, querier, queryfrontend) to 2, so that we can drain infra nodes without violating the PDBs for those components.
changelog.
> Bump replica count for LokiStack read path to 2 for 1x.demo

- component/loki.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/50_loki_operator_metrics_token.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/50_loki_operator_metrics_token.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_loki_operator_metrics_token.yaml
> Manually generate missing Loki Operator metrics token

- class/defaults.yml
- component/loki.libsonnet
- component/loki_workaround.libsonnet
- component/workaround-scripts/wal-check.sh
- tests/golden/defaults/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
Sometimes loki-ingester pods get stuck when the pods are not cleanly restarted. This workaround checks for long startup times of ingester pods and cleans checkpoint directory to non-existing indexes in `/tmp/wal` directory of the pod.
changelog.
> Workaround for stuck loki-ingester pods

- class/defaults.yml
- tests/golden/defaults/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
This helps to prevent NodeDrainStuck alerts from firing in the situation where the first ingester pod doesn't come up during the maintenance.
changelog.
> Run the loki ingester workaround every 10 minutes

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- component/main.jsonnet
- tests/forwardingonly.yml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/00_namespace.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
> Support deploying only LogForwarding

- class/defaults.yml
- component/config_forwarding.libsonnet
- component/config_logging.libsonnet
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- lib/openshift4-logging.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/master.yml
> Refactor ClusterLogging and ClusterLogForwarder generation code

- alerts.txt
- class/defaults.yml
- component/alertrules.libsonnet
- component/extracted_alerts/release-5.9/collector_prometheus_alerts.yaml
- component/extracted_alerts/release-5.9/elasticsearch_operator_prometheus_alerts.yaml
- component/extracted_alerts/release-5.9/lokistack_prometheus_alerts.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/golden/elasticsearch/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/elasticsearch/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
> Update to OpenShift Logging 5.9

- component/alertrules.libsonnet
- component/main.jsonnet
- component/utils.libsonnet
- tests/golden/elasticsearch/openshift4-logging/openshift4-logging/20_subscriptions.yaml
> Fix elasticsearch-operator deprecated in stable-5.9

- class/defaults.yml
- component/logmetrics.libsonnet
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
In logging version 5.8 and newer versions, the LogFileMetricExporter is no longer deployed with the collector by default. You must manually create a LogFileMetricExporter custom resource (CR) to generate metrics from the logs produced by running containers.
If you do not create the LogFileMetricExporter CR, you may see a No datapoints found message in the OpenShift Container Platform web console dashboard for Produced Logs.
changelog.
> Support creating LogFileMetricsExporter CR

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- class/defaults.yml
- component/config_forwarding.libsonnet
- docs/modules/ROOT/pages/how-tos/upgrade-v3.x-v4.x.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/elasticsearch.yml
- tests/forwardingonly.yml
- tests/golden/forwardingonly/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/legacy/openshift4-logging/console-patching/openshift4_console_params.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/00_namespace.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/30_cluster_logging.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_ingester_fix.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_logstore.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_netpol.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_operator_metrics_token.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_rbac.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/50_loki_stack.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/60_collector_alerts.yaml
- tests/golden/legacy/openshift4-logging/openshift4-logging/60_lokistack_alerts.yaml
- tests/legacy.yml
- tests/master.yml
- tests/multilineerr.yml
With this commit configuring the ClusterLogForwarder resource will be done with a new parameter `openshift4_logging.clusterLogForwarder`, which will follow the upstream convention / spec.
The old parameter `openshift4_logging.clusterLogForwarding` is deprecated, but existing legacy config will be respected.
changelog.
> Refactor configuration of ClusterLogForwarder

- class/defaults.yml
- component/config_forwarding.libsonnet
- component/main.jsonnet
- component/utils.libsonnet
- docs/modules/ROOT/pages/how-tos/enable-multi-forwarder.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/golden/master/openshift4-logging/openshift4-logging/10_operator_group.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/32_namespace_logforwarding.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/32_namespace_rolebinding.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/32_namespace_serviceaccount.yaml
- tests/master.yml
> Support multi-log-forwarder

- component/config_forwarding.libsonnet
This commit ensures that infrastructure or application logs pipelines only get configured when enabled in forwarding only mode.
changelog.
> Fix configuring LogForwarding pipelines only when needed

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/master/openshift4-logging/openshift4-logging/99_secrets.yaml
- tests/master.yml
> Support creating secrets in component

- class/defaults.yml
- component/alertrules.libsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Support patching upstream alert rules

- component/config_forwarding.libsonnet
- tests/golden/legacy/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/32_namespace_logforwarding.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/31_cluster_logforwarding.yaml
Add `SkipDryRunOnMissingResource=true` to `ClusterLogForwarder` so that the initial sync of the openshift4-logging ArgoCD app can succeed.
changelog.
> Fix initial sync for `ClusterLogForwarder` resources

- component/log_forwarder.libsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/golden/defaults/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder.yaml
- tests/golden/multilineerr/openshift4-logging/openshift4-logging/40_log_forwarder_rbac.yaml
The ClusterLogForwarder did not have the definitions and permissions to insert logs into the builtin Loki Stack.
changelog.
> Fix Logs not sent to LokiStack

- component/main.jsonnet
- tests/golden/defaults/openshift4-logging/openshift4-logging/20_subscriptions.yaml
- tests/golden/master/openshift4-logging/openshift4-logging/20_subscriptions.yaml
Change OLM channel of cluster-observability-operator to `stable`, 
as the documented `developement` channel got dropped.
changelog.
> Update cluster-observability-operator to stable/v1.x
